### ISSUE TITLE
Words to include

### ISSUE THREAD

**Issue by jxu** [jxu/Word2VecDemo#1]
If including all words, the model has undesirable "words" like `</s>`, 9e9e9, vertical-align, etc.

So to be strict the model can only include alphabetical character words. This excludes numbers, hyphenated words, words with apostrophes, etc. 

This changes about 500/10000 of the words actually

**Comment by jxu** [comment]
@touretzkyds `grep -n refrigerator model.txt` shows refrigerator at position 20044. I have already filtered out a lot of words so maybe I will just expand the model size.

Here is the filtered words list currently, produced with `cut -d' ' -f1 wordvecs10k.txt`: [alphawords10k.txt](https://github.com/jxu/Word2VecDemo/files/6633310/alphawords10k.txt) They all ook reasonable, although there are a fair amount of proper nouns (indicated with a capital letter).

**Comment by jxu** [comment]
As an experiment I changed the word list to only lowercase words. I don't have a strong justification for getting rid of proper nouns though. It gets rid of common words like the names of countries and months.

**Comment by touretzkyds** [comment]
I think it makes sense to include day and month names, and maybe country names, as these are limited categories and occur frequently in text. There are an infinite number of first and last names, city names, and county names, so the simiplest thing would be to disallow them all. We can always revisit this later if it turns out we really need to include some of these names.

**Comment by jxu** [comment]
> 10,000 words is clearly not enough. The words "over", "under", and "above" are missing. Can you switch to one of the larger vocabulary datasets? Also, it would be good to display the vocabulary size somewhere. How many words are left after filtering out the proper nouns?

This is due to the NLTK stop word removal as part of the preprocessing of the corpus from NLPL word embeddings repository. I think all models had stop words removed: http://vectors.nlpl.eu/repository/latest.json under corpora

**Comment by touretzkyds** [comment]
The dataset used by the original demo does include "over", "under", and "above". Why do you prefer this other dataset?

Also, let's increase the limit from 10K to 20K. I want "refrigerator" and "toaster".

**Comment by touretzkyds** [comment]
We're also missing "poodle", "beagle", and "chihuahua", which the original demo has.

**Comment by jxu** [comment]
I can switch to the original dataset, but my understanding was stopword removal good for semantic NLP tasks for which stopwords can produce spurious matches. But for the case of nearest word matching, maybe we should leave them in. Do you want to switch back to the original dataset? Then I can rerun the nearest neighbors search too.

**Comment by touretzkyds** [comment]
I think it's interesting to look at the representations of stopwords; you can't do machine translation without them. But the original dataset also has its flaws; it's heavily computer-centric, so the closest words to "apple" are computer words, not fruit words.

Can we find a dataset that includes stopwords but is richer than the dataset we're using now?

**Comment by jxu** [comment]
Do you know the source of the original dataset?
I can try using the pre-trained fasttext models. If we want even more control, I can try training on a custom dataset, though I don't know how long it will take.

**Comment by touretzkyds** [comment]
Our paper said "The text8 corpus (Mahoney 2006a) was used to train the embeddings used by our demo."
http://mattmahoney.net/dc/textdata.html

Please don't invest any effort in training a custom dataset. This demo is already taking longer than I expected. We need to get the demo finished so we can move on to the next one.

**Comment by jxu** [comment]
Here are the 1M tokens from the fasttext model from https://fasttext.cc/docs/en/english-vectors.html
[1m_words.txt](https://github.com/jxu/Word2VecDemo/files/6698863/1m_words.txt)

There are a lot of tokens, including many proper nouns and even non-English words. "over" appears at position 94 but "chihuahua" only appears at position 111806 (not including filtering out numbers and all other stuff)

**Comment by touretzkyds** [comment]
Okay. Let's stick with the text8 corpus for now, but filter out the non-words and proper nouns, except days of week, months of year, and continent and country names.

**Comment by jxu** [comment]
Here is the new word list of 50k words, but only alphabetical characters including capital letters. All the words you are looking for should be in here, though some dog breeds are capitalized.

[words50k.txt](https://github.com/jxu/Word2VecDemo/files/6698973/words50k.txt)

**Comment by touretzkyds** [comment]
This looks promising, but there are acronyms in there (BMA, PMA, RTC, UNC), and separate entries for "rampage" and "Rampage", and for "surprised" and "Surprised". And lots of proper names. So some cleanup is called for.

**Comment by jxu** [comment]
I don't know if the acronyms or proper names are necessarily an issue. For words that are the same letters but different capitalization, I guess I can use the more common word and filter out words with alternate capitalizations.

**Comment by jxu** [comment]
New words list, using most common word casing [words50k.txt](https://github.com/jxu/Word2VecDemo/files/6719546/words50k.txt)

**Comment by touretzkyds** [comment]
I did a git pull and the demo is now broken in a new way:
````
word2vec.js:60 Assertion failed: king not in vecs
(anonymous) @ word2vec.js:60
word2vec.js:60 Assertion failed: queen not in vecs
(anonymous) @ word2vec.js:60
word2vec.js:60 Assertion failed: prince not in vecs
(anonymous) @ word2vec.js:60
word2vec.js:60 Assertion failed: princess not in vecs
(anonymous) @ word2vec.js:60
word2vec.js:249 TypeError: Cannot read property 'sub' of undefined
    at word2vec.js:80
    at Array.map (<anonymous>)
    at createFeature (word2vec.js:80)
    at main (word2vec.js:208)
(anonymous) @ word2vec.js:249
````
This is getting annoying. Make the demo work, please.

**Comment by jxu** [comment]
This is the same issue as in #2, I am in the process of using the compressed vectors. See #2

**Comment by jxu** [comment]
I noticed the page freezes up for a few seconds when running the code to unpack the gzip. I tried to move the vector unpacking to a Promise-returning function, but it still freezes the browser. If it becomes a problem for slower computers, then I will have to move the heavy code to a Web Worker.

**Comment by jxu** [comment]
fastText also has a similar dataset using sub-words if we want to use morphological information https://classic.d2l.ai/chapter_natural-language-processing/fasttext.html
