### ISSUE TITLE
Word select functionality

### ISSUE THREAD

**Issue by jxu** [jxu/Word2VecDemo#10]
Described in #7

**Comment by jxu** [comment]
Weird issue with click https://github.com/plotly/plotly.js/issues/3106

**Comment by jxu** [comment]
Weird issue with click https://github.com/plotly/plotly.js/issues/1025

**Comment by jxu** [comment]
I added the point select and vector replace functionality. Axis click events are not supported by plotly natively and it requires the use of some lower-level d3 interfacing. 

The heatmap may also adjust its coloring based on what words are present. This may be undesirable.

**Comment by touretzkyds** [comment]
I can click on a word in the 3D plot to select it, and it turns red. But there does not appear to be a way to deselect it. It would be good if I could deselect it by clicking in empty space.

**Comment by jxu** [comment]
Clicking empty space is also used for rotating the view. 
I implemented deselect by clicking on the already selected point. This should be intuitive for users.

**Comment by jxu** [comment]
Clicking points is buggy due to the workaround from plotly/plotly.js#1025 
I may have to change it to drawing a new plot like I did for adding new words

**Comment by touretzkyds** [comment]
Clicking on the point to deselect it is an acceptable solution. Thanks.

**Comment by jxu** [comment]
I've tested the online version and it seems to work reasonably well ( but fyi the console will spit out an ugly error due to the plotly bug).

**Comment by jxu** [comment]
To elaborate: clicking on heatmap y axis label uses some plotly and d3 trickery. Since this is not a native plotly function, d3 is used to bind click events to the low-level plotly SVG element `g.yaxislayer-above`. Every time the plots are replotted (which currently is always the case for the scatterplot because the new point text showed up too small #9), the click events need to be rebound, so `plotly_afterplot` event handler is used.
