### ISSUE TITLE
Display of axis basis vectors

### ISSUE THREAD

**Issue by touretzkyds** [jxu/Word2VecDemo#13]
We have two computed basis vectors. By default they are age and gender, but in later extensions to this demo we will allow users to define their own basis vectors.

We need a way to copy a basis vector into the Vector Display area so the user can examine its components. One way to do this would be to have two little buttons marked with the dimension names, e.g., "Age" and "Gender". Clicking on a button causes it to glow red and makes that vector the "active" vector. Then clicking on one of the six vector display slots would copy the vector into that slot, set the slot label to "[Age]" or "[Gender]", and reset the button. If the user clicks on the button while it is red, this should reset the button.

**Comment by jxu** [comment]
I was seeing if it was possible to implement the same axis label clicking functionality on the 3D plot but I think this is done through WebGL not SVG like the 2D plots so probably not possible. So I'll try the buttons, which would also deselect the point and I think treating the basis vector as another pseudo-word is the cleanest approach

**Comment by jxu** [comment]
I am reworking the functionality to take into account #16. Still WIP

**Comment by touretzkyds** [comment]
Clicking on the Age and Gender buttons doesn't seem to do anything.

**Comment by jxu** [comment]
I added selection of axis vectors that is similar to the previous behavior of clicking points. Feature axis pseudo-words are indicated by brackets and use colored red text in the plot.
