### ISSUE TITLE
vector component 249

### ISSUE THREAD

**Issue by touretzkyds** [jxu/Word2VecDemo#15]
Vector component 249 seems to be strongly positive for every word I can think of. What's going on here? For what words is it negative?

"dishonor" has a value of 0.077 and that's the least positive word I can find.

**Comment by jxu** [comment]
Here is a list of the top 20 negative words using unnormalized vectors. They appear to be Wikipedia-specific terms like usernames or bot names:

```
ann -2.345
cluebot -1.8886
alt -1.4804
viaf -1.2934
afded -1.1482
tildes -1.1453
sturat -1.0592
proded -0.9953
giano -0.9953
kotbot -0.9784
reverted -0.9757
stevebaker -0.9579
rjensen -0.9505
jackofoz -0.9484
hcfa -0.9433
mnm -0.9418
drmies -0.9415
enwiki -0.9378
bracketbot -0.9339
shortsummary -0.9322
```
cluebot, kotbot, and bracketbot are wikipedia bots. enwiki is a special syntax term for usernames. Words like alt, tildes, reverted, and shortsummary are wikipedia-specific.

**Comment by jxu** [comment]
The fasttext model is "1 million word vectors trained on Wikipedia 2017, UMBC webbase corpus and statmt.org news dataset"

**Comment by jxu** [comment]
I was curious so I tried the words with most positive dim 249 and interestingly shows some non-English words

[('san', 0.6615),
 ('cervical', 0.6657),
 ('della', 0.6665),
 ('qur', 0.6702),
 ('sri', 0.6742),
 ('abdel', 0.6781),
 ('gove', 0.6782),
 ('puerto', 0.6784),
 ('dear', 0.6996),
 ('dalai', 0.7035),
 ('micron', 0.7256),
 ('gosh', 0.7306),
 ('amino', 0.7329),
 ('suu', 0.7343),
 ('los', 0.7412),
 ('amanda', 0.742),
 ('grand', 0.7543),
 ('boko', 0.7575),
 ('buenos', 0.7873),
 ('goodbye', 0.8563)]

**Comment by jxu** [comment]
Here are some other dimensions for fun.

Dim 0 (dimension index is arbitrary I think) neg values are a weird mix of internet terms and organizations, not sure about pos values


[('sowell', -0.5513),
 ('bir', -0.5445),
 ('gastropod', -0.4795),
 ('sneezing', -0.4695),
 ('iz', -0.4683),
 ('readme', -0.4673),
 ('hse', -0.4573),
 ('delanoygabsadds', -0.4418),
 ('bile', -0.4375),
 ('torrent', -0.4316),
 ('gcse', -0.4281),
 ('iplayer', -0.4259),
 ('primers', -0.4218),
 ('asme', -0.4213),
 ('syllabi', -0.4178),
 ('cpsc', -0.4139),
 ('nadir', -0.4131),
 ('broaden', -0.4119),
 ('urdu', -0.4083),
 ('iupac', -0.4025),

 ('squadrons', 0.4322),
 ('unfaithful', 0.436),
 ('dragoons', 0.4441),
 ('undetected', 0.4484),
 ('illusory', 0.4532),
 ('mammogram', 0.4539),
 ('baptised', 0.4547),
 ('bracelet', 0.455),
 ('serait', 0.4615),
 ('angelique', 0.4625),
 ('tanning', 0.4628),
 ('eugenie', 0.4741),
 ('covenants', 0.4772),
 ('alamos', 0.4791),
 ('synchrotron', 0.4814),
 ('vivien', 0.4887),
 ('aerodrome', 0.491),
 ('conceals', 0.4922),
 ('clovis', 0.5122),
 ('hacienda', 0.5212)]

dim 52, very negative. neg words are wikipedia terms and foreign terms, pos words are common verbs

[('serait', -2.9519),
 ('hasteurbot', -1.7325),
 ('delanoygabsadds', -1.7002),
 ('bambots', -1.6538),
 ('spacewatch', -1.6533),
 ('zl', -1.6523),
 ('coibot', -1.6317),
 ('mergeaccount', -1.5954),
 ('prokonsul', -1.5925),
 ('jackbot', -1.5663),
 ('taxdetails', -1.5439),
 ('genloc', -1.5386),
 ('internetarchivebot', -1.5294),
 ('wister', -1.5149),
 ('nuvola', -1.4951),
 ('readme', -1.4893),
 ('frodesiak', -1.455),
 ('serols', -1.441),
 ('userreport', -1.4408),
 ('iitalk', -1.4345),

 ('helps', -0.4628),
 ('leads', -0.4621),
 ('counterparts', -0.4614),
 ('attempts', -0.4607),
 ('approaches', -0.4598),
 ('features', -0.456),
 ('image', -0.4556),
 ('ie', -0.4548),
 ('should', -0.4541),
 ('starts', -0.4529),
 ('continues', -0.4515),
 ('becomes', -0.4509),
 ('contribution', -0.4464),
 ('appears', -0.431),
 ('begins', -0.4308),
 ('may', -0.429),
 ('apparently', -0.4284),
 ('became', -0.4283),
 ('seemed', -0.4238),
 ('tends', -0.4213)]


dim 232: mix of wikipedia and foreign location terms
[('serait', -1.0604),
 ('tfded', -0.5198),
 ('rkd', -0.4469),
 ('roedd', -0.4267),
 ('afded', -0.4151),
 ('kotbot', -0.3762),
 ('ahh', -0.3542),
 ('cluebot', -0.3506),
 ('satyrbot', -0.3383),
 ('delanoygabsadds', -0.3207),
 ('taxdetails', -0.3109),
 ('mergeaccount', -0.2974),
 ('stboti', -0.2843),
 ('mnm', -0.2722),
 ('csdwarnbot', -0.2502),
 ('gmina', -0.2429),
 ('ahhh', -0.2416),
 ('dywedodd', -0.2383),
 ('yourpaintings', -0.2111),

 ('proded', -0.2072),
 ('angeles', 0.5804),
 ('nadu', 0.5887),
 ('monoxide', 0.5957),
 ('kyi', 0.5968),
 ('talk', 0.6037),
 ('rican', 0.6092),
 ('century', 0.6108),
 ('jiabao', 0.6132),
 ('lankan', 0.6168),
 ('lumpur', 0.6292),
 ('laden', 0.6358),
 ('aires', 0.6384),
 ('janeiro', 0.6499),
 ('sciences', 0.6661),
 ('pradesh', 0.6759),
 ('jintao', 0.6928),
 ('dioxide', 0.7159),
 ('prnewswire', 0.7249),
 ('rid', 0.7426),
 ('userreport', 0.8824)]
