### ISSUE TITLE
Arrows in 3D display

### ISSUE THREAD

**Issue by touretzkyds** [jxu/Word2VecDemo#18]
Can we draw arrows in the 3D plot?

For the vector arithmetic mode, when we have king - man + woman = queen, it would be good to draw an arrow from king to man and another arrow from woman to the king-man+woman result. Each arrow should be the color of its destination node.

**Comment by jxu** [comment]
I think it is possible to draw line segments. I'm not sure about arrows. According to https://stackoverflow.com/a/63316665 it is possible to repurpose a 3d cone plot as arrow ends, but I'm not sure how this will look.

**Comment by touretzkyds** [comment]
Lines might be good enough, since we also have color coding to distinguish the head node from the tail node.

**Comment by jxu** [comment]
Here is an example of the lines drawn in blue

![Screenshot from 2021-08-15 00-14-41](https://user-images.githubusercontent.com/7989982/129466925-81c11afe-7b6d-497a-9456-24d18f316e02.png)

**Comment by jxu** [comment]
I opened https://github.com/plotly/plotly.js/issues/5891, in the meantime this is the best I could make which I think looks good enough

![Screenshot from 2021-08-15 00-56-08](https://user-images.githubusercontent.com/7989982/129467575-6f7b3819-2c54-4960-807a-88f5884be7ff.png)

**Comment by touretzkyds** [comment]
This does look good, but king-->man should be man-->king so that it's parallel with woman-->(king-man+woman).

Also, the unnormalized version of king-man+woman seems to be the right thing to use, based on the plots you showed.

**Comment by touretzkyds** [comment]
Just tried prince-boy+girl and got princess with beautiful parallel arrows. Well done!
