### ISSUE TITLE
axis range

### ISSUE THREAD

**Issue by touretzkyds** [jxu/Word2VecDemo#24]
It turns out that [-0.3, 0.3] is too narrow a range for the gender axis. The word "surgeons" doesn't appear in the 3D plot because its gender projection is greater than 0.3.

I guess we need to increase the gender range to [-0.4, 0.4].

**Comment by touretzkyds** [comment]
"computer" and "refrigerator" also no longer show up in the 3D display. Not sure what's going on here.

**Comment by touretzkyds** [comment]
I tried defining a "royalty" dimension using pairs like man/king and boy/prince, and once again the [-0.3, 0.3] axis range proved too narrow. I guess we should go back to auto-scaling but force the scale to be symmetric, e.g., turn [-0.2, 0.4] into [-0.4, 0.4].

**Comment by touretzkyds** [comment]
It would be good if you could fix #24 today because I have to generate figures for the EAAI paper. I'm not so worried about the axis label issue.

**Comment by jxu** [comment]
I think the autorange is still the best because I don't know if in the implementation of fasttext the individual dimensions will be centered on zero. I can include special cases for small number of points if that is your concern.

**Comment by jxu** [comment]
In https://github.com/jxu/Word2VecDemo/commit/d5a605ef58531e5b092e6b4b2313d55b2a204fca I reverted the fixed axis ranges for now.

**Comment by touretzkyds** [comment]
Looks good! Thanks for the quick response on this. I think we'll leave things as they are, and I'll revisit the symmetry issue if I get another student to continue working on this. But we're in a pretty good place right now.
