### ISSUE TITLE
Precompute nearest words list

### ISSUE THREAD

**Issue by jxu** [jxu/Word2VecDemo#4]
Benchmarking the original demo in Firefox showed that most time in browser was spent computing the closest word neighbors. The algorithm used was simply two loops, O(n^2) for top 10 words. Actually maybe O(n^2 log n) for sorting the top words list or using a heap. This is okay for our n=10k or 100k to precompute once and then serve without making things too complicated. In fact, I don't even know with this dimensional data whether a structure like a k-d tree will even work due to the curse of dimensionality.

It can either be implemented in numpy or experimentally for me in Node. I'll probably write it in numpy since I know it will be reasonably efficient for vector operations. There is probably an efficient Node implementation for vectors.

**Comment by touretzkyds** [comment]
Doing this precomputation for the selected vocabulary sounds like a good idea.

Keep in mind that when we implement vector arithmetic we will need to find the 10 closest words to the result vector, but that's only O(n) for the distances plus O(n log n) for the sort. And since we only care about the top 10 results and don't need the entire sorted list, there are probably ways to compute that more quickly than a full sort.

**Comment by touretzkyds** [comment]
I'm concerned that the 10K word list you're using does not include "refrigerator". What else is missing? We should eventually find something with a larger vocabulary, but without all the garbage entries  you found in our original dataset.

**Comment by jxu** [comment]
My idea for top k words was maintaining a fixed size max distance heap, so that large distance words are popped as lower distance words come in. However this I believe is only a factor of log k instead of log n.

**Comment by jxu** [comment]
My python and numpy implementation with sorting the list took 10.5 minutes which is ok for current N=10k but would be quite slow for N=20k or N=50k. I'll try the heap method now

**Comment by jxu** [comment]
Actually I profiled the code and as I guessed earlier the sorting took negligible time. I replaced it with a dot product which is equivalent for unit vectors and it ran in 3.5 minutes, probably due to the overhead of euclidean distance rather than any real computational savings. This is good enough for N=10k but for N=20k or 50k I would rewrite it in C or C++ because even with numpy, python has a huge overhead.

**Comment by touretzkyds** [comment]
If it took 3.5 minutes for 10K words, an O(N^2) algorithm should only take 4 times longer for 20K words.  Even 50K words would only take 25 times longer, or 1.5 hours. Just let it run and go to dinner.

**Comment by jxu** [comment]
That is true. Just for fun, I was thinking of how nearest neighbor search could be achieved for high-dimensional space for millions of points. I briefly looked at the current research and it seems like the research is in approximate nearest neighbor algorithms, which does sound quite interesting.

**Comment by jxu** [comment]
For fun I tried to use the max heap method.

Using final list sort:

```
         300295268 function calls (300282299 primitive calls) in 291.676 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1  114.748  114.748  291.677  291.677 nearest_words.py:1(<module>)
 99990001  101.305    0.000  101.305    0.000 {method 'dot' of 'numpy.ndarray' objects}
    10014   57.104    0.006   69.087    0.007 {method 'sort' of 'list' objects}
 99990000   11.983    0.000   11.983    0.000 nearest_words.py:34(<lambda>)
 99994267    5.446    0.000    5.446    0.000 {method 'append' of 'list' objects}
    20106    0.420    0.000    0.420    0.000 {built-in method numpy.array}
    10000    0.258    0.000    0.258    0.000 {built-in method builtins.print}
    10026    0.098    0.000    0.098    0.000 {method 'split' of 'str' objects}
    12565    0.059    0.000    0.059    0.000 {method 'join' of 'str' objects}
    10000    0.038    0.000    0.038    0.000 nearest_words.py:35(<listcomp>)
    10000    0.031    0.000    0.063    0.000 linalg.py:2325(norm)
```

Using heap method takes the same amount of time, but since I already wrote it I'm keeping it:

```
         400205268 function calls (400192299 primitive calls) in 280.743 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1  124.288  124.288  280.744  280.744 nearest_words.py:1(<module>)
 99990001   92.081    0.000   92.081    0.000 {method 'dot' of 'numpy.ndarray' objects}
 99890000   31.230    0.000   31.230    0.000 {built-in method _heapq.heappop}
 99990000   26.224    0.000   26.224    0.000 {built-in method _heapq.heappush}
100014586/100014368    5.861    0.000    5.861    0.000 {built-in method builtins.len}
    20106    0.422    0.000    0.422    0.000 {built-in method numpy.array}
    10000    0.183    0.000    0.183    0.000 {built-in method builtins.print}
    10026    0.096    0.000    0.096    0.000 {method 'split' of 'str' objects}
    10002    0.051    0.000    0.051    0.000 {built-in method builtins.sorted}
    12565    0.037    0.000    0.037    0.000 {method 'join' of 'str' objects}
    10000    0.035    0.000    0.086    0.000 heapq.py:521(nlargest)
    10000    0.031    0.000    0.063    0.000 linalg.py:2325(norm)

```

**Comment by touretzkyds** [comment]
If you're just keeping the 10 closest neighbors, a heap is overkill. You could do better with a simple insertion into a sorted array.

**Comment by jxu** [comment]
Do you mean just keeping an array of top-k words that maintains sorted order? Isn't a heap doing that?

**Comment by touretzkyds** [comment]
Yes, a sorted 10-element array with linear insertion. Plus, if a new element has a greater distance than the current 10th element, you don't need to bother searching the array at all. A heap uses a more complex balanced-tree structure, and the overhead involved in maintaining this introduces a large constant factor that makes the simpler algorithm faster for small datasets.

This issues comes up in k-d trees as well. Some people use k-d trees to implement fast nearest neightbor in high-dimensional spaces, but it turns out that unless you have hundreds of thousands of points, less sophisticated algorithms are actually faster even though they are asymptotically worse.

**Comment by jxu** [comment]
Ok I see. By the way it turns out I implemented my heap inefficiently because it was pushing and popping every element. I'm not sure why I wrote it like that. Now that I correctly checked against the top heap element, it runs faster, in 2.5 min. I can quickly try the sorted array method too.

```
         201130269 function calls (201117300 primitive calls) in 196.390 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1  100.936  100.936  196.391  196.391 nearest_words.py:1(<module>)
 99990001   89.083    0.000   89.083    0.000 {method 'dot' of 'numpy.ndarray' objects}
100014586/100014368    4.912    0.000    4.912    0.000 {built-in method builtins.len}
    20106    0.420    0.000    0.420    0.000 {built-in method numpy.array}
   705001    0.340    0.000    0.340    0.000 {built-in method _heapq.heapreplace}
    10000    0.211    0.000    0.211    0.000 {built-in method builtins.print}
    10026    0.097    0.000    0.097    0.000 {method 'split' of 'str' objects}
    10002    0.054    0.000    0.054    0.000 {built-in method builtins.sorted}
    10000    0.038    0.000    0.093    0.000 heapq.py:521(nlargest)
    12565    0.034    0.000    0.035    0.000 {method 'join' of 'str' objects}
    10000    0.032    0.000    0.064    0.000 linalg.py:2325(norm)
   100000    0.029    0.000    0.029    0.000 {built-in method _heapq.heappush}
```

**Comment by jxu** [comment]
I was thinking about the slowest part of computing all dot products. If N were small enough this could be done all at once with one giant matrix multiplication, but that requires N^2 storage just to store the result. However, I can still do all dot products of word i and all other words, instead of computing dot product of word i vs word j individually. This turns out to be quite a bit faster due to efficient numpy matrix multiplication and takes only 1.3 min on my computer.

cProfile doesn't show numpy operations but most time is spent on the matrix multiplication
```
         101150269 function calls (101137300 primitive calls) in 84.595 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1   63.595   63.595   84.596   84.596 nearest_words.py:1(<module>)
    10000   15.647    0.002   15.647    0.002 nearest_words.py:32(<listcomp>)
100014586/100014368    4.251    0.000    4.252    0.000 {built-in method builtins.len}
    20106    0.415    0.000    0.415    0.000 {built-in method numpy.array}
   705001    0.226    0.000    0.226    0.000 {built-in method _heapq.heapreplace}
    10026    0.095    0.000    0.095    0.000 {method 'split' of 'str' objects}
    10002    0.035    0.000    0.035    0.000 {built-in method builtins.sorted}
    10000    0.031    0.000    0.062    0.000 linalg.py:2325(norm)
    10000    0.029    0.000    0.029    0.000 nearest_words.py:43(<listcomp>)
   100000    0.026    0.000    0.026    0.000 {built-in method _heapq.heappush}
    12565    0.023    0.000    0.023    0.000 {method 'join' of 'str' objects}
    10000    0.021    0.000    0.021    0.000 {built-in method builtins.print}
    10000    0.018    0.000    0.053    0.000 heapq.py:521(nlargest)


```

**Comment by jxu** [comment]
Nearest words hover text is added

**Comment by touretzkyds** [comment]
The hover text should include the reference word as well, just as we do in the original demo. But instead of saying "Original word" it should say "Reference word".

**Comment by jxu** [comment]
Ok. Do we want them to be numbered 1 through 10 also

**Comment by touretzkyds** [comment]
Yes, that's a good idea.

**Comment by jxu** [comment]
added
