### ISSUE TITLE
Original demo down?

### ISSUE THREAD

**Issue by jxu** [jxu/Word2VecDemo#5]
http://www.cs.cmu.edu/~dst/word2vecdemo/demo_till_vecviz_with_color/

I have a stored copy of the code but I wanted to look at some network performance. Mainly to see if CMU's webserver would support gzipped requests which it looks like it does.

**Comment by touretzkyds** [comment]
I deleted some of the old versions because they were taking up a lot of disk space. Use this version:
https://www.cs.cmu.edu/~dst/Word2VecDemo
