### ISSUE TITLE
Add/remove word functionality

### ISSUE THREAD

**Issue by jxu** [jxu/Word2VecDemo#7]
I added a button and text button for adding or removing words. If a word is present in the scatterplot, it is removed, otherwise it is added if it exists as a word vec. There is currently no message to the user if the word is not known - maybe there should be a message or alert popup. 

Not sure how to sync scatter plot and vector explorer since the scatter plot shows 20 words and the vector display would only show 6. How would the user add or remove from the vector display?

**Comment by touretzkyds** [comment]
Yes, we definitely need to tell the user if the word is unknown. Maybe they just made a typo. Or maybe they're testing the demo to see how big the vocabulary is. In any case, we cannot just silently fail.

Here is how the vector explorer is supposed to work. The user first clicks on a point in the 3D plot. The selected point becomes the "current point" and turns red. Whenever there is a current point (a red point), the user can click on one of the 6 vector explorer slots, and that word's vector is copied into that slot, and the current point is cleared.

Aso, adding a word makes it the current point. Deleting a word (any word) clears the current point.

**Comment by jxu** [comment]
I added a message telling the user the result of the operation. Also the plot resets every operation so I am seeing if I can change that to preserve the viewing angle.

**Comment by jxu** [comment]
Turns out it's quite simple to save the viewing angle between operations so I added that.

**Comment by touretzkyds** [comment]
Please update the confirmation/failure message to include the word in question, e.g., it should say "Word 'oven' added" or "Word 'toaster' not found".

**Comment by touretzkyds** [comment]
* After I select a word, I can click on a row in the Vector Visualization area to copy that word vector into that row. Doing so should deselect the word, so it is no longer red in the 3D view.
* After the new vector is copied into the Vector Visualization area, the magnified view should automatically update. Currently it does not update until I move the mouse in the Vector Visualization area.
* It should also be possible to copy a vector into the Vector Visualization area by clicking on a word in the Magnified view. Currently such clicks are ignored.
* If I type a word in the add/remove word text box, I have to then click on the "Add/Remove Word" button to take action. This is fine, but it should also be possible to take the action by pressing Enter in the text box.
* When a word is successfully added or deleted, we should clear the text box.

**Comment by jxu** [comment]
In the process of adding features, the way my code did plotly bindings seemed to cause more and more bindings to happen as a memory leak (I don't know the internals of d3). I think I've fixed it but clicking is still a bit slow due to redrawing the plot and the plotly bug in #10.
