### ISSUE TITLE
New word appears too small

### ISSUE THREAD

**Issue by jxu** [jxu/Word2VecDemo#9]
https://github.com/plotly/plotly.js/issues/5754

**Comment by jxu** [comment]
The workaround appears to be to make a new plot every time the plotted words change, however this doesn't preserve the viewing angle/zoom

**Comment by touretzkyds** [comment]
I thought you had addressed this issue already. Just save the current viewing and and zoom state and restore it after you've made the new plot.

**Comment by jxu** [comment]
I can do that, but I'll have to re-arrange how the click and hover events are bound due to the use of a new plot
